when:
  branch:
    exclude: pages
  event: [push, pull_request]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
#  setup:
#    image: bitnami/git
#    environment:
#      MAIL:
#        from_secrets: mail
#      CODEBERG_TOKEN: codeberg_token
#    commands:
#      - git config --global user.email $MAIL
#      - git config --global user.name "Woodpecker CI"
#      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git public
#    when:
#      event: push

  build:
    image: silex/emacs:alpine-ci
    commands:
      - ./build.sh
    when:
      event: [pull_request, push]

  publish:
    image: bitnami/git
    environment:
      HUGO_OUTPUT: public
      # secrets must be set in Woodpecker configuration
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      # Git configuration
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      # Copy build step output to repository folder
      - cp -ar $HUGO_OUTPUT/. $CI_REPO_NAME/
      # Needed for custom domains
      - cp .domains $CI_REPO_NAME || true # Ignore if it doesn't exist
      # Commit and push all static files with pipeline started timestamp
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_COMMIT_SHA}"
      - git push
    when:
      event: push
