when:
  branch:
    exclude: pages
  event: [push, pull_request]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
#  setup:
#    image: bitnami/git
#    environment:
#      MAIL:
#        from_secrets: mail
#      CODEBERG_TOKEN: codeberg_token
#    commands:
#      - git config --global user.email $MAIL
#      - git config --global user.name "Woodpecker CI"
#      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git public
#    when:
#      event: push

  pre-build:
    image: alpine
    commands:
      - mkdir public
      - chmod -R a+w public
  build:
    image: dfrkp/emacs-latex
    commands:
      - ./build.sh
    when:
      event: [pull_request, push]

  publish:
    image: bitnami/git
    environment:
      MAIL:
        from_secrets: mail
    commands:
      - cd public
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git add -A
      - if ! git diff-index --quiet HEAD; then
      -     git commit -m "Build at $(date -Is)"
      -     if [ $CI_COMMIT_BRANCH = "main" ]; then
      -         git push origin pages
      -     else
      -         echo "Skipping push branch $CI_COMMIT_BRANCH"
      -     fi
      - fi
    when:
      event: push
